# THEOS compilation, install here: https://theos.dev
#IOS Theos Template Komaru
#Jailed (NoJB) Mod Menu Template for iOS Games
#By aq9
#https://github.com/VenerableCode/iOS-Theos-ModMenuTemp-NoJB


ARCHS = arm64
TARGET = iphone:clang:latest:latest

DEBUG = 0
FINALPACKAGE = 1
FOR_RELEASE = 1

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Ranim

$(TWEAK_NAME)_FRAMEWORKS = UIKit Foundation Security QuartzCore CoreGraphics CoreText  AVFoundation Accelerate GLKit SystemConfiguration GameController

$(TWEAK_NAME)_CFLAGS = -fobjc-arc -Wall -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-value -Wno-unused-function
$(TWEAK_NAME)_CCFLAGS = -std=c++17 -fno-rtti -DNDEBUG -Wall -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-writable-strings

$(TWEAK_NAME)_FILES = MenuLoad/ImGuiDrawView.xm $(wildcard MenuLoad/*.mm) $(wildcard Source/*.mm) $(wildcard ImGui/*.mm) $(wildcard ImGui/*.cpp)

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS)/makefiles/aggregate.mk
